In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv("Admission_Predict_Ver1.1.csv")

# Descriptive Data

In [3]:
data.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000
mean,250.500000,316.472000,107.192000,3.114000,3.374000,3.48400,8.576440,0.560000,0.72174
std,144.481833,11.295148,6.081868,1.143512,0.991004,0.92545,0.604813,0.496884,0.14114
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.00000,6.800000,0.000000,0.34000
25%,125.750000,308.000000,103.000000,2.000000,2.500000,3.00000,8.127500,0.000000,0.63000
50%,250.500000,317.000000,107.000000,3.000000,3.500000,3.50000,8.560000,1.000000,0.72000
75%,375.250000,325.000000,112.000000,4.000000,4.000000,4.00000,9.040000,1.000000,0.82000
max,500.000000,340.000000,120.000000,5.000000,5.000000,5.00000,9.920000,1.000000,0.97000

# Mean GRE score of applicants who got admitted into a university with "5" rating

In [8]:
uni_5 = data[data["University Rating"] >= 5]

In [44]:
uni_5["GRE Score"].mean()

327.0238095238095

## We can take this average GRE score, 327/340, as the benchmark score for top tier grad school admission

# Find the mean TOEFL score for each University Rating

In [29]:
data.groupby("GRE Score").mean()

,Serial No.,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
GRE Score,,,,,,,,
290,248.000000,102.000000,2.500000,1.750000,2.250000,7.510000,0.000000,0.460000
293,169.000000,97.000000,2.000000,2.000000,4.000000,7.800000,1.000000,0.640000
294,176.500000,94.000000,1.000000,1.500000,1.750000,7.500000,0.000000,0.475000
295,273.200000,97.600000,1.600000,2.100000,2.100000,7.524000,0.000000,0.512000
296,210.800000,98.200000,1.800000,2.500000,2.600000,7.666000,0.200000,0.522000
297,353.833333,98.333333,2.333333,2.333333,2.666667,7.728333,0.166667,0.498333
298,259.800000,99.000000,2.200000,2.500000,3.000000,7.772000,0.300000,0.507000
299,249.400000,99.500000,2.200000,2.600000,2.650000,7.897000,0.000000,0.537000
300,263.583333,100.166667,2.083333,2.500000,2.500000,7.995833,0.333333,0.595833
301,275.454545,101.090909,2.454545,2.954545,3.000000,8.102727,0.636364,0.624545
302,300.142857,101.714286,2.142857,2.500000,3.071429,7.922857,0.000000,0.558571
303,195.800000,100.800000,2.800000,3.100000,3.200000,8.104000,0.200000,0.590000
304,280.916667,102.250000,2.750000,3.000000,2.833333,8.033333,0.083333,0.570833
305,306.636364,104.545455,2.545455,2.636364,2.954545,8.188182,0.000000,0.624545
306,250.000000,104.571429,2.142857,2.857143,3.000000,8.234286,0.142857,0.642857
307,238.100000,105.700000,2.700000,3.200000,3.450000,8.087000,0.300000,0.627000
308,262.000000,105.769231,2.769231,3.115385,3.423077,8.216154,0.384615,0.655385
309,269.111111,104.777778,2.777778,2.888889,3.166667,8.165556,0.000000,0.637778
310,263.818182,104.454545,2.636364,2.772727,3.409091,8.201818,0.363636,0.667273
311,276.562500,102.875000,2.437500,3.000000,3.156250,8.246875,0.625000,0.665000
312,268.291667,104.625000,2.500000,2.979167,3.354167,8.387083,0.416667,0.685417
313,241.833333,102.916667,2.750000,3.041667,3.250000,8.528333,0.250000,0.684167
314,214.812500,105.500000,2.937500,3.281250,3.562500,8.432500,0.312500,0.696250
315,251.461538,104.153846,2.307692,2.961538,2.846154,8.265385,0.153846,0.645385
316,222.277778,104.666667,2.555556,2.972222,3.333333,8.342778,0.388889,0.661667
317,265.933333,105.000000,2.466667,3.200000,3.100000,8.394667,0.466667,0.690000
318,257.750000,106.833333,2.666667,3.291667,3.666667,8.625000,0.583333,0.702500
319,283.250000,106.500000,3.083333,3.208333,3.166667,8.607500,0.583333,0.729167
320,269.250000,108.750000,3.250000,3.562500,3.812500,8.743125,0.750000,0.790000
321,257.529412,110.000000,3.588235,3.617647,4.000000,8.849412,0.882353,0.805294
322,218.000000,109.588235,3.764706,3.794118,3.705882,8.778824,0.823529,0.784706
323,260.461538,109.692308,3.846154,3.846154,3.961538,8.910769,0.846154,0.785385
324,279.869565,110.347826,3.826087,3.804348,3.695652,8.920435,0.913043,0.813913
325,237.600000,110.866667,3.533333,3.600000,3.700000,8.914667,0.800000,0.742667
326,228.916667,111.666667,3.500000,3.875000,3.583333,9.066667,0.916667,0.822500
327,259.176471,111.294118,3.823529,3.852941,3.970588,8.932941,0.764706,0.801176
328,250.888889,112.888889,4.222222,4.500000,3.888889,9.172222,1.000000,0.848889
329,208.300000,113.000000,3.900000,4.150000,4.200000,9.159000,1.000000,0.853000
330,302.750000,115.500000,4.375000,4.625000,4.000000,9.332500,1.000000,0.906250
331,197.555556,116.222222,4.444444,4.388889,4.333333,9.377778,1.000000,0.918889
332,223.000000,115.750000,3.875000,4.375000,4.250000,9.221250,0.875000,0.893750
333,219.750000,116.750000,4.750000,4.750000,4.375000,9.517500,1.000000,0.930000
334,189.000000,117.500000,4.625000,4.250000,4.250000,9.328750,1.000000,0.916250
335,237.250000,116.750000,4.750000,4.750000,4.500000,9.625000,1.000000,0.940000
336,190.200000,117.200000,4.800000,4.500000,4.300000,9.580000,1.000000,0.948000
337,249.000000,117.500000,4.500000,4.750000,4.750000,9.760000,1.000000,0.940000
338,179.250000,117.500000,4.250000,4.000000,4.750000,9.437500,1.000000,0.920000
339,109.333333,116.333333,4.666667,4.166667,4.000000,9.753333,0.666667,0.936667
340,186.000000,116.555556,4.555556,4.666667,4.500000,9.604444,1.000000,0.947778

In [47]:
data.groupby("University Rating")["TOEFL Score"].mean()

University Rating
1    100.205882
2    103.444444
3    106.314815
4    110.961905
5    113.438356
Name: TOEFL Score, dtype: float64

## Conclusion; We can see a positive correlation between school tiers and toefl scores, and can use 113/120 as the mean benchmark sore for top tier schools

# Find the average research score per university rating

In [42]:
data.groupby("University Rating")["Research"].mean()

University Rating
1    0.294118
2    0.293651
3    0.537037
4    0.780952
5    0.876712
Name: Research, dtype: float64

## Conclusion: We can see that there is a positive correlation with average research score and university rating in grad school application, with the exception of lower tier schools